apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: alaudaDeployService
  annotations:
    alauda.io/displayName.zh-CN: zj更新服务
    alauda.io/displayName.en: Update service
    alauda.io/description.zh-CN: 使用指定的镜像以及镜像版本等参数，更新指定集群的特定服务
    alauda.io/description.en: Update a service using docker image
    alauda.io/readme.zh-CN: 使用指定的镜像以及镜像版本等参数，更新指定集群的特定服务
    alauda.io/readme.en: Update a service using docker image
    alauda.io/version: v0.1
    alauda.io/style.icon: 
  labels:
    category: CICD
spec:
  engine: graph
  withSCM: false
  options:
    timeout: 1800
  stages:
    - name: DeployService
      tasks:
        - name: DeployService
          type: public/alaudaDeployService
  values:
    tasks:
      DeployService:
        args:
          useServiceYaml: false
  arguments:
    - displayName:
        zh-CN: "基本信息"
        en: "Basic Info"
      items:
        - name: containerInfo 
          schema:
            type: alauda.io/newk8scontainermix
          binding:
            - DeployService.args.containerInfo
          display:
            type: alauda.io/newk8scontainermix
            name:
              zh-CN: "容器"
              en: "Container"
            description:
              zh-CN: |
                即将被更新的服务的容器,这里包含了一下字段
                1. 集群名称，表示即将更新的服务容器所在的集群
                2. 命名空间，表示即将更新的服务容器所在的集群的名空间
                3. 服务名称，表示即将更新的服务容器所在的集群的服务名称
                4. 容器名称，表示即将更新的服务容器的名称
              en: |
                The containers in the service which will be updated contain the following fields
                1.  The cluster name in which the service will be updated
                2.  The namespace in which the service will be updated
                3.  The service name which will be updated
                4.  The container name in the service which will be updated
          required: true
        - name: command
          schema:
            type: string
          binding:
            - DeployService.args.command
          display:
            type: string
            name:
              zh-CN: "接入点"
              en: "Entrypoint"
            description:
              zh-CN: "容器启动时执行的接入点，如果不指定，则使用原有服务接入点"
              en: "Entrypoint of container, , using original service command if it is empty"
          required: false
        - name: args
          schema:
            type: string
          binding:
            - DeployService.args.args
          display:
            type: string
            name:
              zh-CN: "执行命令"
              en: "Run Command"
            description:
              zh-CN: "容器启动时执行的命令，如果不指定，则使用原有服务命令"
              en: "Command of container, using original service command if it is empty"
          required: false
        - name: image
          schema:
            type: alauda.io/imagerepositorymix
          binding:
            - DeployService.args.image
          display:
            type: alauda.io/imagerepositorymix
            name:
              zh-CN: "更新使用的镜像仓库"
              en: "Image repository to use"
            description:
              zh-CN: "更新使用的镜像仓库, 如果使用yaml 来部署更新，则会自动更新该镜像对应的容器"
              en: "Image repository to use"
          required: true
        - name: "imageTag"
          schema:
            type: string
          binding:
            - DeployService.args.imageTag
          display:
            type: alauda.io/imagetag
            name:
              zh-CN: "镜像版本"
              en: "Image tag"
            description:
              zh-CN: "更新服务时使用的镜像版本, 例如 latest"
              en: "image tag"
          required: true
          default: latest
        - name: env
          schema:
            type: alauda.io/k8senv
          binding:
            - DeployService.args.env
          display:
            type: alauda.io/k8senv
            name:
              zh-CN: "环境变量"
              en: "Environment variables"
            description:
              zh-CN: "环境变量"
              en: "Environment variables"
            related: containerInfo
        - name: envFrom
          schema:
            type: array
            items:
              type: object
          binding:
            - DeployService.args.envFrom
          display:
            type: alauda.io/k8sconfigmap
            name:
              zh-CN: "ConfigMap"
              en: "ConfigMap"
            related: containerInfo
        - name: autoRollbackOnFail
          schema:
            type: boolean
          binding:
            - DeployService.args.autoRollbackOnFail
          display:
            type: boolean
            name:
              zh-CN: 自动回滚
              en: "Auto Rollback"
          required: true
          default: true
        - name: timeout
          schema:
            type: int
          binding:
            - DeployService.args.timeout
          display:
            type: int
            name:
              zh-CN: "超时时间（秒）"
              en: "Timeout (s)"
            description:
              zh-CN: "超时时间（秒）"
              en: "Timeout (s)"
          required: true
